{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eureka.serviceAccountName" . }}
  labels:
{{ include "eureka.labels" . | indent 4 }}
{{- end -}}
