dependencies:
  - name: mysql
    version: 0.1.0
    repository: charts
    condition: mysql.enabled
  - name: redis-ha
    alias: redis
    version: 0.1.0
    repository: charts
    condition: redis.enabled