dependencies:
  - name: mysql
    version: 0.1.0
    repository: charts
    condition: mysql.enabled
  - name: mysql
    alias: mysql-test
    version: 0.1.0
    repository: charts
    condition: mysql-test.enabled