{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "provider.serviceAccountName" . }}
  labels:
{{ include "provider.labels" . | indent 4 }}
{{- end -}}
