# Default values for jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pi4k8s/jenkins
  tag: 2.222.3
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""


env:
  JAVA_OPTS: "-Xmx1024m -Xms1024m"

service:
  type: ClusterIP
  port: 8080

serviceAgent:
  type: NodePort
  port: 50000
  nodePort: 50000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 20Gi
  # storageClass: "-"
