apiVersion: v1
kind: Service
metadata:
  name: {{ include "consumer.fullname" . }}
  labels:
{{ include "consumer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "consumer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
