{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "consumer.serviceAccountName" . }}
  labels:
{{ include "consumer.labels" . | indent 4 }}
{{- end -}}
