apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "gogs.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  name:  {{ template "gogs.fullname" . }}-config

data:
    app.ini: |
        APP_NAME = {{ $.Values.config.appName }}
        RUN_USER = git
        RUN_MODE = prod

        [database]
        DB_TYPE  = sqlite3
        HOST     = 127.0.0.1:3306
        NAME     = gogs
        USER     = root
        PASSWD   =
        SSL_MODE = disable
        PATH     =  {{ $.Values.config.database.path }}

        [repository]
        ROOT = /data/git/gogs-repositories

        [server]
        DOMAIN           = {{ $.Values.config.server.domain }}
        HTTP_PORT        = 3000
        ROOT_URL         = {{ $.Values.config.server.rootUrl }}
        DISABLE_SSH      = false
        SSH_PORT         = 22
        START_SSH_SERVER = false
        OFFLINE_MODE     = false

        [mailer]
        ENABLED = true
        HOST    = {{ $.Values.config.mailer.host }}
        FROM    = {{ $.Values.config.mailer.from }}
        USER    = {{ $.Values.config.mailer.user }}
        PASSWD  = {{ $.Values.config.mailer.passwd }}

        [service]
        REGISTER_EMAIL_CONFIRM = true
        ENABLE_NOTIFY_MAIL     = true
        DISABLE_REGISTRATION   = true
        ENABLE_CAPTCHA         = false
        REQUIRE_SIGNIN_VIEW    = false

        [picture]
        DISABLE_GRAVATAR        = false
        ENABLE_FEDERATED_AVATAR = false

        [session]
        PROVIDER = file

        [log]
        MODE      = console, file
        LEVEL     = Info
        ROOT_PATH = /app/gogs/log

        [security]
        INSTALL_LOCK = true
        SECRET_KEY   = {{ $.Values.config.security.securityKey }}