# Default values for redis-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: crisidev/redis-exporter
  tag: linux-arm64
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  redis_addr: common-utilities-redis:6379

service:
  type: ClusterIP
  port: 9121

resources:
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
