dependencies:
  - name: mysqld-monitor
    alias: mysqld
    version: 0.1.0
    repository: charts
    condition: mysqld.enabled
  - name: mysqld-monitor
    alias: mysqld-a
    version: 0.1.0
    repository: charts
    condition: mysqld-a.enabled
  - name: mysqld-monitor
    alias: mysqld-b
    version: 0.1.0
    repository: charts
    condition: mysqld-b.enabled
  - name: redis-monitor
    alias: redis
    version: 0.1.0
    repository: charts
    condition: redis.enabled