apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  name:  {{ template "mysql.fullname" . }}-config

data:
    my.cnf: |
        [mysqld]
        ## 设置server_id，一般设置为IP，注意要唯一
        server_id=100
        ## 复制过滤：也就是指定哪个数据库不用同步（mysql库一般不同步）
        binlog-ignore-db=mysql
        ## 开启二进制日志功能，可以随便取，最好有含义（关键就是这里了）
        log-bin=replicas-mysql-bin
        ## 为每个session分配的内存，在事务过程中用来存储二进制日志的缓存
        binlog_cache_size= {{ $.Values.config.binlog_cache_size }}
        ## 主从复制的格式（mixed,statement,row，默认格式是statement）
        binlog_format=mixed
        ## 二进制日志自动删除/过期的天数。默认值为0，表示不自动删除。
        expire_logs_days={{ $.Values.config.expire_logs_days }}
        innodb_large_prefix=ON
        innodb_lock_wait_timeout = {{ $.Values.config.innodb_lock_wait_timeout }}
        innodb_default_row_format=DYNAMIC
        innodb_log_file_size= {{ $.Values.config.innodb_log_file_size }}
        max_allowed_packet={{ $.Values.config.max_allowed_packet }}
        lower_case_table_names={{ $.Values.config.lower_case_table_names }}
        innodb_buffer_pool_size={{ $.Values.config.max_innodb_buffer_pool_size }}
        max_connections={{ $.Values.config.max_connection }}
        max_connect_errors=10000
        default-storage-engine=INNODB

        wait_timeout = {{ $.Values.config.wait_timeout }}
        interactive_timeout = {{ $.Values.config.interactive_timeout }}

        #Encoding
        collation-server = {{ $.Values.config.encoding }}_bin
        init-connect='SET NAMES {{ $.Values.config.encoding }}'
        character-set-server = {{ $.Values.config.encoding }}

        log_error=error.log