{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mysql.serviceAccountName" . }}
  labels:
{{ include "mysql.labels" . | indent 4 }}
{{- end -}}
