# Default values for gogs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: autarchprinceps/gogs-arm64
  tag: latest
  pullPolicy: IfNotPresent

initImage:
  repository: pi4k8s/sqlite3:3.22.0-ubuntu-18-04

service:
  type: ClusterIP
  port: 3000

serviceSSH:
  type: ClusterIP
  port: 22

config:
  appName: Gogs
  database:
    path: data/gogs.db
  server:
    domain: sshgogs.ub.com
    rootUrl: http://gogs.ub.com
  mailer:
    host: smtp.yeah.net:111
    from:  email@example.com
    user:  email@example.com
    passwd: passwd
  security:
    securityKey: ox9xSFKsQyXFHOJ

ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - gogs.ub.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
#  cpu: 100m
#  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
  # storageClass: "-"


